# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"embed_data_mask": "01_augment.ipynb",
         "SAINTMixUp": "01_augment.ipynb",
         "SAINTCutMix": "01_augment.ipynb"}

modules = ["augmentation.py"]

doc_url = "https://muellerzr.github.io/fastai_saint/"

git_url = "https://github.com/muellerzr/fastai_saint/tree/main/"

def custom_doc_links(name): return None
